server:
  port: 8081

spring:
  application:
    name: identity-service
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/healthcare_identity}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history
    validate-on-migrate: true
    clean-disabled: false
    repair-on-migrate: true
  
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
      bindings:
        userCreatedOutput-out-0:
          destination: user-created
          contentType: application/json
          group: identity-service-group

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
    bulkheads:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      userService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  retry:
    instances:
      userService:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.RestClientException
          - java.io.IOException
          - java.net.SocketTimeoutException
  ratelimiter:
    instances:
      userService:
        registerHealthIndicator: true
        limitForPeriod: 20
        limitRefreshPeriod: 1s
        timeoutDuration: 3s
  bulkhead:
    instances:
      userService:
        maxConcurrentCalls: 20
        maxWaitDuration: 10ms

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: public
      paths-to-match: /**
      paths-to-exclude: /api/v1/people/check-cpf, /api/v1/people/check-crm

jwt:
  secret: ${JWT_SECRET:c7fd2e876d9d46c2a3d8e5c2f6a95b3a8f4b7c1e9a2d5b8e3f6c9d2a5b8e1f4}
  expiration: 86400000 # 24 hours
