spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/healthcare_facility
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKERS:localhost:9092}
      bindings:
        appointmentCreatedInput:
          destination: appointment-created
          contentType: application/json
          group: facility-service-group
        referralCreatedInput:
          destination: referral-created
          contentType: application/json
          group: facility-service-group

services:
  identity:
    url: ${IDENTITY_SERVICE_URL:http://localhost:8081}
  people:
    url: ${PEOPLE_SERVICE_URL:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
    bulkheads:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      identityService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
      peopleService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
  ratelimiter:
    instances:
      identityService:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 3s
      peopleService:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 3s
  bulkhead:
    instances:
      identityService:
        maxConcurrentCalls: 10
        maxWaitDuration: 10ms
      peopleService:
        maxConcurrentCalls: 10
        maxWaitDuration: 10ms

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  circuitbreaker:
    enabled: true
