server:
  port: 8083

spring:
  application:
    name: scheduling-service
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/healthcare_scheduling}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history
    validate-on-migrate: true
    clean-disabled: false
  
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
      bindings:
        appointmentCreatedOutput:
          destination: appointment-created
          contentType: application/json
          group: scheduling-service-group
        referralCreatedOutput:
          destination: referral-created
          contentType: application/json
          group: scheduling-service-group

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
    bulkheads:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      userService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  retry:
    instances:
      userService:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.RestClientException
          - java.io.IOException
          - java.net.SocketTimeoutException
  ratelimiter:
    instances:
      userService:
        registerHealthIndicator: true
        limitForPeriod: 20
        limitRefreshPeriod: 1s
        timeoutDuration: 3s
  bulkhead:
    instances:
      userService:
        maxConcurrentCalls: 20
        maxWaitDuration: 10ms

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

services:
  facility:
    url: ${FACILITY_SERVICE_URL:http://facility-service:8084}
  identity:
    url: ${IDENTITY_SERVICE_URL:http://identity-service:8081}
  people:
    url: ${PEOPLE_SERVICE_URL:http://people-service:8082}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  packages-to-scan: br.com.fiap.tech.scheduling.controller
